language: node_js
sudo: false
node_js:
  - "iojs-v1"
  - "iojs-v2"

script: "npm run test-ci"
after_script:
  - "npm run benchmark"
  - "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
